import { Product } from './types';

export const SNEAKER_PRODUCTS: Product[] = [
  // ---------------------------------------------------------
  // SECCIÓN: DAMA
  // ---------------------------------------------------------
  {
    id: "nike-dunk-low-brown-sail",
    name: "Nike Dunk Low Cacao",
    brand: "Nike",
    category: "Urbano",
    gender: "Dama",
    price: 200000,
    sizes: [35, 36, 37, 38, 39],
    colors: ["Café Cacao"],
    image: "/productos/mujer/nike_sb_dunk_cocoa.jpg",
    rating: 4.9,
    isHot: true,
    description: "El colorway más codiciado de la temporada. Cuero premium café chocolate sobre una base color crema (Sail), perfecto para combinar con tonos tierra de manera espectacular."
  },
  {
    id: "on-cloudrunner-lavender-storm",
    name: "On Cloud",
    brand: "OnCloud",
    category: "Deportivo",
    gender: "Dama",
    price: 190000,
    sizes: [35, 36, 37, 38, 39],
    colors: ["Gris"],
    image: "/productos/mujer/oncloud_gris.jpg",
    rating: 4.8,
    isHot: true,
    description: "Zapatillas On Cloudrunner para mujer. Tienen suela con sistema CloudTec y espuma Helion que amortiguan tus pasos. Gris claro con detalles blancos."
  },
  {
    id: "on-cloudrunner-beige-sunset",
    name: "On Cloudrunner Sand Beige & Pink",
    brand: "OnCloud",
    category: "Deportivo",
    gender: "Dama",
    price: 190000,
    sizes: [35, 36, 37, 38, 39],
    colors: ["Arena/Rosa Vibrante"],
    image: "/productos/mujer/oncloud_cafe.jpg",
    rating: 4.8,
    isNew: true,
    description: "Tonos arena combinados con unos cordones rosa vibrante que destacan en cualquier trote o caminata. Ligereza, ventilación y amortiguación excepcionales."
  },
  {
    id: "adidas-superstar-maroon-teddy",
    name: "Adidas Superstar",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 190000,
    sizes: [35, 36, 37, 38, 39],
    colors: ["Blanco/Vino Tinto"],
    image: "/productos/mujer/adidas_superstar_vinotinto.jpg",
    rating: 4.9,
    isNew: true,
    description: "El diseño resalta por sus franjas laterales y talón en tono vinotinto. Las franjas incluyen un patrón de costuras decorativas blancas. Tienen un estampado de un oso en la parte trasera y en la etiqueta de la lengüeta. Traen un llavero metálico redondo con el mismo diseño del oso y cordones color vinotinto."
  },
  {
    id: "nike-zoom",
    name: "Nike Zoom Vomero Plus",
    brand: "Nike",
    category: "Deportivo",
    gender: "Dama",
    price: 185000,
    sizes: [36, 37, 38, 39],
    colors: ["Blanco con Rosa"],
    image: "/productos/mujer/nike_zoom.jpg",
    rating: 4.9,
    isHot: true,
    description: "Estas zapatillas para mujer tienen una cubierta textil tejida en color blanco con el logo lateral magenta. Destacan por una entresuela muy gruesa de espuma ZoomX con un borde exterior rosado y translúcido."
  },
  {
    id: "adidas-samba",
    name: "Adidas Samba OG",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 180000,
    sizes: [36, 37, 38, 39],
    colors: ["Café"],
    image: "/productos/mujer/adidas_sambas_cafe.jpg",
    rating: 4.7,
    isHot: true,
    description: "Esta variante presenta un exterior café con el nombre del modelo impreso y las tres franjas laterales en blanco Trae la suela de goma plana que identifica a esta referencia."
  },
  {
    id: "puma-fenty",
    name: "Puma Fenty",
    brand: "Puma",
    category: "Urbano",
    gender: "Dama",
    price: 180000,
    sizes: [36, 37, 38, 39],
    colors: ["Rojo Chicago", "Azul Royal", "Negro/Oro Premium"],
    image: "/productos/mujer/puma_fenty.jpg",
    rating: 4.9,
    isHot: true,
    description: "Calzado urbano que resalta por su diseño clásico en gamuza negra con la franja lateral blanca en contraste. Su principal característica es la suela gruesa de plataforma en goma estriada que eleva tu silueta. Es una opción versátil para tus looks casuales."
  },
  {
    id: "asics-turquesa",
    name: "Asics Superblast 2",
    brand: "Asics",
    category: "Deportivo",
    gender: "Dama",
    price: 195000,
    sizes: [36, 37, 38, 39],
    colors: ["Turquesa"],
    image: "/productos/mujer/asics_dama_azulverde.png",
    rating: 4.9,
    isHot: true,
    description: "Luce el diseño running más codiciado del momento con el máximo confort. Esta versión importada de alta calidad replica fielmente los acabados y el llamativo color Wave Teal. Cuenta con una entresuela de excelente amortiguación ideal para tus caminatas, entrenamientos ligeros o looks urbanos diarios. Estilo de alta gama y comodidad superior en cada paso."
  },
  {
    id: "asics-morado",
    name: "Asics Superblast 2",
    brand: "Asics",
    category: "Deportivo",
    gender: "Dama",
    price: 195000,
    sizes: [36, 37, 38, 39],
    colors: ["Bold Magenta"],
    image: "/productos/mujer/asics_dama_morado_fuscia.png",
    rating: 4.9,
    isHot: true,
    description: "Atrévete a destacar con el colorway más enérgico e impactante de la temporada. Esta versión importada de alta calidad replica detalladamente el electrizante contraste entre magenta, rosa glo y el acento verde menta de los nuevos Superblast 2. Su entresuela de máximo volumen te brinda una amortiguación ultra suave en tus actividades diarias, entrenamientos o caminatas. El balance perfecto entre estilo urbano atrevido y confort superior."
  },
  {
    id: "adidas-samba-og",
    name: "Adidas Samba OG Brown", 
    brand: "Adidas",
    category: "Deportivo",
    gender: "Dama",
    price: 180000,
    sizes: [36, 37, 38, 39],
    colors: ["Turquesa"],
    image: "/productos/mujer/samba_dama_og_cafe.png",
    rating: 4.9,
    isHot: true,
    description: "Eleva tu estilo urbano con esta edición especial. Destaca por su base en tono crema suave, llamativas tres franjas en contraste marrón moca y su icónica suela de goma retro."
  },
  {
    id: "adidas-samba-coleccion",
    name: "Adidas Sambas OG",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 180000,
    sizes: [36, 37, 38, 39],
    colors: ["Leopardo", "Negro", "Marrón Claro", "Café Chocolate", "Burdeos", "Vinotinto"],
    image: "/productos/mujer/samba_tigre.jpg",
    images: [
      "/productos/mujer/samba_negros.jpg",
      "/productos/mujer/samba_cafee.jpg",
      "/productos/mujer/samba_cafem.jpg",
      "/productos/mujer/samba_burdeo.jpg",
      "/productos/mujer/samba_vinotinto.jpg",
    ],
    colorImages: {
      Leopardo: "/productos/mujer/samba_tigre.jpg",
      Negro: "/productos/mujer/samba_negros.jpg",
      "Marrón Claro": "/productos/mujer/samba_cafee.jpg",
      "Café Chocolate": "/productos/mujer/samba_cafem.jpg",
      Burdeos: "/productos/mujer/samba_burdeo.jpg",
      Vinotinto: "/productos/mujer/samba_vinotinto.jpg",
    },
    rating: 4.9,
    isHot: true,
    isNew: true,
    description: "Eleva tu estilo urbano con esta edición especial. Destaca por su base en tono crema suave, llamativas tres franjas en contraste marrón moca y su icónica suela de goma retro."
  },
  {
    id: "nike-coleccion-dunk",
    name: "Nike SB Dunk Low",
    brand: "Nike",
    category: "Urbano",
    gender: "Dama",
    price: 200000,
    sizes: [36, 37, 38, 39],
    colors: ["Café", "Sail/Plum Eclipse/Diffused Taupe", "Phantom / Metallic Gold / Sanddrift", "Verde Oliva"],
    image: "/productos/mujer/dunk_cafe.jpg",
    images: [
      "/productos/mujer/dunk_rosa.jpg",
      "/productos/mujer/dunk_rosado.jpg",
      "/productos/mujer/dunk_verde.jpg",
    ],
    colorImages: {
      Café: "/productos/mujer/dunk_cafe.jpg",
      "Sail/Plum Eclipse/Diffused Taupe": "/productos/mujer/dunk_rosa.jpg",
      "Phantom / Metallic Gold / Sanddrift": "/productos/mujer/dunk_rosado.jpg",
      "Verde Oliva": "/productos/mujer/dunk_verde.jpg",
    },
    rating: 4.9,
    isHot: true,
    description: "Eleva tu estilo urbano con esta edición especial. Destaca por su base en tono crema suave, llamativas tres franjas en contraste marrón moca y su icónica suela de goma retro."
  },
  {
    id: "adidas-forum",
    name: "Adidas Forum",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 180000,
    sizes: [36, 37, 38, 39],
    colors: ["Beige"],
    image: "/productos/mujer/forum_dama.jpg",
    rating: 4.9,
    isHot: true,
    description: "Eleva tu estilo urbano con esta edición especial."
  },
  {
    id: "adidas-samba-og-verde",
    name: "Adidas Samba OG",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 190000,
    sizes: [36, 37, 38, 39],
    colors: ["Verde"],
    image: "/productos/mujer/samba_verde.jpg",
    rating: 4.9,
    isHot: true,
    description: "Estas zapatillas son las Adidas Samba OG en la combinación de colores verde y blanco con suela de goma (Collegiate Green)"
  },
  {
    id: "nike-vomero-plus",
    name: "Nike Vomero Plus 'ZoomX'",
    brand: "Nike",
    category: "Deportivo",
    gender: "Dama",
    price: 185000,
    sizes: [36, 37, 38, 39],
    colors: ["Azul/Aguamarina", "Lila/Rosa", "Blanco/Rosa/Rojo"],
    image: "/productos/mujer/nike-vomero-azul.jpg",
    images: [
      "/productos/mujer/nike-vomero-lila.jpg",
      "/productos/mujer/nike-vomero-rosarojo.jpg"
    ],
    colorImages: {
      "Azul/Aguamarina": "/productos/mujer/nike-vomero-azul.jpg",
      "Lila/Rosa": "/productos/mujer/nike-vomero-lila.jpg",
      "Blanco/Rosa/Rojo": "/productos/mujer/nike-vomero-rosarojo.jpg",
    },
    rating: 4.9,
    isNew: true,
    description: "El equilibrio perfecto entre velocidad y estilo urbano. Diseñadas con una malla ligera de alto rendimiento y la revolucionaria amortiguación ZoomX de entresuela gruesa, que te ofrece el máximo retorno de energía y una pisada ultra suave en cada kilómetro."
  },
  {
    id: "new-balance-530-plataforma",
    name: "New Balance 530 Plataforma",
    brand: "New Balance",
    category: "Deportivo",
    gender: "Dama",
    price: 185000,
    originalPrice: 195000,
    sizes: [36, 37, 38, 39],
    colors: ["Azul Oscuro", "Lila", "Celeste", "Plateado y Rosado Pastel", "Negro"],
    image: "/productos/mujer/nb-530-azulmarino.jpg",
    images: [
      "/productos/mujer/nb-530-lila.jpg",
      "/productos/mujer/nb-530-celeste.jpg",
      "/productos/mujer/nb-530-rosapastel.jpg",
      "/productos/mujer/nb-530-negro.jpg",
    ],
    colorImages: {
      "Azul Oscuro": "/productos/mujer/nb-530-azulmarino.jpg",
      "Lila": "/productos/mujer/nb-530-lila.jpg",
      "Celeste": "/productos/mujer/nb-530-celeste.jpg",
      "Plateado y Rosado Pastel": "/productos/mujer/nb-530-rosapastel.jpg",
      "Negro": "/productos/mujer/nb-530-negro.jpg",
    },
    rating: 4.9,
    isNew: true,
    description: "Calzado de estilo retro inspirado en los años 2000. Esta versión destaca por combinar su clásica base de malla con superposiciones metalizadas y una suela de plataforma robusta que eleva tu silueta, ofreciendo un look urbano, moderno y extra cómodo."
  },
  {
    id: "adidas-samba-mary-jane-cafe",
    name: "Adidas Samba Mary Jane",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 180000,
    originalPrice: 195000,
    sizes: [36, 37, 38, 39],
    colors: ["Café"],
    image: "/productos/mujer/samba-jane.jpg",
    rating: 4.8,
    isNew: true,
    description: "Esta innovadora silueta transforma las icónicas Samba en un elegante diseño Mary Jane. Presenta un exterior café chocolate con correa ajustable, finas perforaciones y sutiles detalles dorados. Su suela de goma plana aporta versatilidad y confort para looks casuales y muy femeninos."
  },
  {
    id: "adidas-campus-mule-plataforma",
    name: "Adidas Campus Mule",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 195000,
    sizes: [36, 37, 38, 39],
    colors: ["Negro", "Café", "Beige"],
    image: "/productos/mujer/campus-pantufla-negro.jpg",
    images: [
      "/productos/mujer/campus-pantufla-cafe.jpg",
      "/productos/mujer/campus-pantufla-beife.jpg",
    ],
    colorImages: {
      Negro: "/productos/mujer/campus-pantufla-negro.jpg",
      Café: "/productos/mujer/campus-pantufla-cafe.jpg",
      Beige: "/productos/mujer/campus-pantufla-beife.jpg",
    },
    rating: 4.8,
    isNew: true,
    description: "Esta versión destalonada transforma los clásicos Adidas Campus en un cómodo diseño tipo mule o pantufla. Presenta un exterior en gamuza con cordones gruesos y forro suave. Su suela de plataforma eleva tu silueta, ofreciendo un estilo relajado, versátil y de máximo confort."
  },
  {
    id: "on-running-cloud-dama",
    name: "On Running CloudTec",
    brand: "OnCloud",
    category: "Deportivo",
    gender: "Dama",
    price: 195000,
    sizes: [36, 37, 38, 39],
    colors: ["Gris y Lila", "Beige", "Café y Amarillo", "Blanco y Naranja"],
    image: "/productos/mujer/on-gris-lila.jpg",
    images: [
      "/productos/mujer/on-beige.jpg",
      "/productos/mujer/on-cafe-amarillo.jpg",
      "/productos/mujer/on-blanco-naranja.jpg",
    ],
    colorImages: {
      "Gris y Lila": "/productos/mujer/on-gris-lila.jpg",
      "Beige": "/productos/mujer/on-beige.jpg",
      "Café y Amarillo": "/productos/mujer/on-cafe-amarillo.jpg",
      "Blanco y Naranja": "/productos/mujer/on-blanco-naranja.jpg",
    },
    rating: 4.8,
    isNew: true,
    description: "Zapatillas deportivas que redefinen la comodidad. Destacan por su innovadora suela con tecnología CloudTec (perforaciones) que absorbe impactos y brinda una pisada ultra suave. Su diseño de malla transpirable y estética moderna las hace perfectas para running o uso diario prolongado."
  },
  {
    id: "adidas-adizero-blanco-dama",
    name: "Adidas Adizero",
    brand: "Adidas",
    category: "Deportivo",
    gender: "Dama",
    price: 195000,
    sizes: [36, 37, 38, 39],
    colors: ["Blanco y Plateado"],
    image: "/productos/mujer/adizero-blancob.jpg",
    rating: 4.9,
    isNew: true,
    description: "Zapatillas de alto rendimiento diseñadas para la velocidad. Presentan un exterior en malla ligera semi-translúcida y una robusta suela aerodinámica con amortiguación avanzada. Su diseño deportivo y dinámico ofrece máxima comodidad, ideal para entrenamientos o looks casuales."
  },
  {
    id: "adidas-spezial-red",
    name: "Adidas Handball Spezial",
    brand: "Adidas",
    category: "Urbano",
    gender: "Dama",
    price: 190000,
    sizes: [36, 37, 38, 39],
    colors: ["Rojo"],
    image: "/productos/mujer/adidas-spezial-rojo.webp",
    rating: 4.9,
    isNew: true,
    description: "Estas zapatillas son las Adidas Handball Spezial en la icónica combinación de gamuza color rojo vibrante con las tres rayas blancas y suela de goma retro"
  },
  {
    id: "on-cloudmonster-negro-menta",
    name: "On Running Cloudmonster",
    brand: "OnCloud",
    category: "Deportivo",
    gender: "Dama",
    price: 200000,
    sizes: [36, 37, 38, 39],
    colors: ["Negro/Menta"],
    image: "/productos/mujer/on-cloudmonster-negro-menta.webp",
    rating: 4.9,
    isHot: true,
    description: "Zapatillas On Running Cloudmonster en color negro con detalles en verde menta. Cuentan con suela de máxima amortiguación y tecnología CloudTec."
  },
  {
    id: "nike-blazer-mid-77-blanco-negro",
    name: "Nike Blazer Mid '77 Vintage",
    brand: "Nike",
    category: "Urbano",
    gender: "Dama",
    price: 180000,
    sizes: [36, 37, 38, 39],
    colors: ["Blanco", "Negro"],
    image: "/productos/mujer/nike-blazer-mid-blanco-negro.webp",
    rating: 4.8,
    isHot: true,
    description: "Zapatillas clásicas Nike Blazer Mid '77 en estilo bota. Diseño en cuero blanco con el logo Swoosh en negro, lengüeta de espuma expuesta y detalles en gamuza gris en la punta frontal."
  },

  // ---------------------------------------------------------
  // SECCIÓN: CABALLERO
  // ---------------------------------------------------------
  {
    id: "adidas-badbo10",
    name: "Adidas Badbo 1.0",
    brand: "Adidas",
    category: "Urbano",
    gender: "Caballero",
    price: 200000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Café"],
    image: "/productos/hombre/adidas_badbo_10_cafe.jpg",
    rating: 4.8,
    isNew: true,
    description: "Es la primera zapatilla de la línea exclusiva de Bad Bunny en colaboración con la marca. El bordado azul en el talón señala el número de serie de una edición limitada a 1994 pares a nivel mundial. La cantidad fue elegida en honor al año de nacimiento del artista. El diseño destaca por sus paneles de gamuza café con recortes triangulares sobre una base clara y el uso de cordones gruesos."
  },
  {
    id: "campus-bad-cafe",
    name: "Campus Bad Bunny",
    brand: "Adidas",
    category: "Urbano",
    gender: "Caballero",
    price: 190000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Café"],
    image: "/productos/hombre/campus_bad_cafe.jpg",
    rating: 4.8,
    isNew: true,
    description: "Este par destaca por su exterior de gamuza el diseño de doble lengüeta el cuello acolchado grueso y la etiqueta con el logo del artista."
  },
  {
    id: "adidas-badbo-hombre",
    name: "Adidas BadBo 1.0",
    brand: "Adidas",
    category: "Urbano",
    gender: "Caballero",
    price: 200000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Gris"],
    image: "/productos/hombre/adidas_badbo_1.0_blancasl.jpg",
    images: ["/productos/hombre/adidas_badbo_1.0_blancas.jpg"],
    rating: 4.6,
    isNew: true,
    description: "Estas zapatillas combinan paneles de gamuza con recortes triangulares y detalles bordados en azul en el talón. Tienen cordones gruesos y doble lengüeta."
  },
  {
    id: "jordan-hombre-retro",
    name: 'Jordan 1 Mid "Come Fly With Me"',
    brand: "Jordan",
    category: "Urbano",
    gender: "Caballero",
    price: 180000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Negros"],
    image: "/productos/hombre/jordan_retro_hombre.png",
    rating: 4.9,
    isHot: true,
    description: "Eleva tu estilo urbano con esta edición especial. Destaca por su base negra mate, llamativas costuras rojas en contraste y el icónico Swoosh brillante en relieve."
  },
  {
    id: "mind-001",
    name: "Sandalias Mind 001",
    brand: "Nike",
    category: "Urbano",
    gender: "Caballero",
    price: 180000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Varios"],
    image: "/productos/hombre/mind_hombre.jpg",
    images: ["/productos/hombre/mind_hombre1.jpg"],
    rating: 4.9,
    isHot: true,
    description: "Estas son sandalias tipo mule Nike Mind 001, reconocibles por sus 22 nodos de espuma articulados en la suela para estimulación sensorial."
  },
  {
    id: "on-cloud",
    name: "On Cloudvista 2",
    brand: "OnCloud",
    category: "Deportivo",
    gender: "Caballero",
    price: 195000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Azul", "Gris Glaciar y Negro"],
    image: "/productos/hombre/on-cloud-azul.jpg",
    images: ["/productos/hombre/on-cloud-ng.jpg"],
    colorImages: {
      Azul: "/productos/hombre/on-cloud-azul.jpg",
      "Gris Glaciar y Negro": "/productos/hombre/on-cloud-ng.jpg",
    },
    rating: 4.9,
    isHot: true,
    description: "On Cloudvista 2 es una zapatilla de trail running optimizada para terrenos mixtos y senderos moderados."
  },
  {
    id: "nike-af1-supreme",
    name: "AF1 x Supreme",
    brand: "Nike",
    category: "Urbano",
    gender: "Caballero",
    price: 175000,
    originalPrice: 190000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Blanco"],
    image: "/productos/hombre/af1-supreme.jpg",
    rating: 4.9,
    isHot: true,
    description: "Air Force One en colaboración con Supreme."
  },
  {
    id: "nike-zoom-gris",
    name: 'Nike Zoom "Have a Nike Day"',
    brand: "Nike",
    category: "Deportivo",
    gender: "Caballero",
    price: 180000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Gris"],
    image: "/productos/hombre/nike-zoom-happy.jpeg",
    rating: 4.5,
    isHot: true,
    description: "Nike Zoom en malla transpirable gris. Cuenta con suela roja, acentos en negro y el detalle de carita sonriente en el talón."
  },
  {
    id: "nike-dunk-low-suede-panda",
    name: "Nike Dunk Low Suede Black/White",
    brand: "Nike",
    category: "Urbano",
    gender: "Caballero",
    price: 180000,
    sizes: [40, 41, 42, 43, 44],
    colors: ["Negro"],
    image: "/productos/hombre/nike-dunk-suede-bn.jpeg",
    images: ["/productos/hombre/nike-dunk-suede-bn-1.jpeg"],
    rating: 4.8,
    isHot: true,
    description: "Silueta clásica Dunk Low: capellada completamente en gamuza (suede) en contraste negro y blanco roto. Incluye detalles de caja de edición especial."
  },

  // ---------------------------------------------------------
  // SECCIÓN: UNISEX
  // ---------------------------------------------------------
  {
    id: "adidas-forum-low-strap-black",
    name: "Adidas Forum Low Strap Black & White",
    brand: "Adidas",
    category: "Urbano",
    gender: "Unisex",
    price: 185000,
    originalPrice: 200000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Blanco/Negro"],
    image: "/productos/mujer/adidas_forum_negras.jpeg",
    rating: 4.9,
    isNew: true,
    description: "La combinación icónica de blanco con las tres rayas negras. Ajuste seguro mediante la correa clásica Forum, con entresuela de caucho adherente y un estilo impecable."
  },
  {
    id: "adidas-forum-low-strap-blue",
    name: "Adidas Forum Low Strap Royal Blue",
    brand: "Adidas",
    category: "Urbano",
    gender: "Unisex",
    price: 185000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Blanco/Azul Rey"],
    image: "/productos/mujer/adidas_forum_azul.jpeg",
    rating: 4.7,
    isNew: true,
    description: "Estilo retro con vibras de baloncesto de los 80. Detalles en azul rey sobre cuero blanco que le dan un toque llamativo, elegante y deportivo a tus outfits de dama."
  },
  {
    id: "new-balance-9060",
    name: "New Balance 9060",
    brand: "New Balance",
    category: "Urbano",
    gender: "Unisex",
    price: 195000,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Gris Nube", "Negro"],
    image: "/productos/unisex/new_balance_9060_beige.jpg",
    images: ["/productos/unisex/new_balance_9060_negras.webp"],
    rating: 4.7,
    isNew: true,
    description: "Este calzado resalta por su estructura robusta y su entresuela ondulada con tecnología de amortiguación ABZORB. Tienes dos opciones disponibles. La primera tiene una base de malla transpirable con gamuza beige y detalles grises. La segunda ofrece un diseño oscuro que mezcla malla y gamuza negra con el logo lateral gris."
  },
  {
    id: "gazelle-azul-blanco",
    name: "Adidas Gazelle",
    brand: "Adidas",
    category: "Urbano",
    gender: "Unisex",
    price: 180000,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Mezcla Azul con Blanco"],
    image: "/productos/unisex/gazelle_hom_muj.webp",
    rating: 4.7,
    isNew: true,
    description: "Estos tenis Adidas Gazelle destacan por su diseño clásico en blanco con icónicas franjas azul marino"
  },
  {
    id: "tiger-onituska",
    name: "Tiger Onituska",
    brand: "Onitsuka Tiger",
    category: "Urbano",
    gender: "Unisex",
    price: 200000,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Amarillo"],
    image: "/productos/unisex/tiger_hom_mujer.webp",
    rating: 4.7,
    isNew: true,
    description: "Son unos tenis Onitsuka Tiger modelo Mexico 66 en color amarillo con rayas negras."
  },
  {
    id: "vision-unisex",
    name: "Vision Street Wear",
    brand: "Vision Street Wear",
    category: "Urbano",
    gender: "Unisex",
    price: 195000,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Negra"],
    image: "/productos/unisex/vision_hombre_mujer.webp",
    rating: 4.7,
    isNew: true,
    description: "Estos tenis son del modelo Vision Street Wear, reconocidos por su diseño clásico en blanco y negro."
  },
  {
    id: "nike-zoom-x-happy",
    name: "Nike Zoom X",
    brand: "Nike",
    category: "Urbano",
    gender: "Unisex",
    price: 170000,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Negra"],
    image: "/productos/unisex/nike-zoom-x.webp",
    rating: 4.7,
    isNew: true,
    description: "Zapatillas para correr de alto rendimiento con amortiguación ZoomX reactiva y un diseño urbano con detalles divertidos."
  },
  {
    id: "nb-530-unisex",
    name: "New Balance 530",
    brand: "New Balance",
    category: "Urbano",
    gender: "Unisex",
    price: 175000,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["Negra"],
    image: "/productos/unisex/nb-530-azul-blanco.webp",
    images: ['/productos/unisex/nb-530-blue-white.webp'],
    rating: 4.7,
    isNew: true,
    description: "Zapatillas deportivas New Balance 530."
  }
];

// ---------------------------------------------------------
// FILTROS GENERADOS DINÁMICAMENTE
// ---------------------------------------------------------
// Extraemos las categorías y marcas directamente del array principal
// usando Set para evitar duplicados. De esta forma nunca tendrás
// que mantener estas listas a mano.

export const CATEGORIES = ['Todos', ...new Set(SNEAKER_PRODUCTS.map(p => p.category))];
export const BRANDS = ['Todas', ...new Set(SNEAKER_PRODUCTS.map(p => p.brand))];